internal/printer/printer.go, internal/printer/printer_test.go
This changes the printer to emit numeric literal separators.
=> Emit numeric literal separators

internal/checker/checker.go
=> Fix circularity in `isTypeParameterPossiblyReferenced`

internal/checker/flow.go
=> chore: update flow.go

internal/lsp/lsproto/_generate/generate.mjs, internal/lsp/lsproto/lsp_generated.go
=> Allow unknown LSP enum values

_extension/package.json, _extension/src/extension.ts, cmd/tsgo/lsp.go, cmd/tsgo/main.go, internal/pprof/pprof.go
add support for getting pprof profiles of LSP.
context: https://discord.com/channels/1298076816732328006/1349171342628618374
=> add -pprofDir profiling to LSP

internal/lsp/converters.go, internal/lsp/server.go
I have no idea how I forgot to do this.
=> Actually use positonEncoding in position converter

internal/bundled/embed.go, internal/vfs/iovfs/iofs.go, internal/vfs/osvfs/os.go, internal/vfs/vfs.go, internal/vfs/vfstest/vfstest.go, internal/vfs/vfstest/vfstest_test.go
`vfs.Remove(path)` will remove `path` (and all its contents if `path` is a dir)
=> add 'Remove()' to vfs

internal/ast/utilities.go
https://github.com/microsoft/TypeScript/blob/29e6d6689dfb422e4f1395546c1917d07e1f664d/src/compiler/utilities.ts#L2738-L2739
=> Fix resolution of type of `void` keyword

internal/execute/outputs.go, internal/execute/tsc_test.go, testdata/baselines/reference/tsc/commandLine/Parse-watch-interval-option-without-tsconfig.json.js, testdata/baselines/reference/tsc/commandLine/Parse-watch-interval-option.js, testdata/baselines/reference/tsc/commandLine/does-not-add-color-when-NO_COLOR-is-set.js, testdata/baselines/reference/tsc/commandLine/help.js, testdata/baselines/reference/tsc/commandLine/show-help-with-ExitStatus.DiagnosticsPresent_OutputsSkipped-when-host-cannot-provide-terminal-width.js, testdata/baselines/reference/tsc/commandLine/show-help-with-ExitStatus.DiagnosticsPresent_OutputsSkipped.js
This PR ports more of `tsc help` from `strada`.
=> Port more of tsc help from strada

.github/workflows/ci.yml, Herebyfile.mjs
This is a lot easier to manage.
=> Use env vars for herebyfile options in CI

internal/checker/utilities.go
=> Speed up compareNodes on nodes within the same file

internal/execute/export_test.go, internal/execute/verifytscwatch_test.go, internal/execute/watch.go, internal/execute/watcher.go, testdata/baselines/reference/tscWatch/commandLineWatch/watch-with-no-tsconfig.js
=> fix `--watch` crash if no tsconfig found

internal/checker/relater.go, testdata/baselines/reference/compiler/subtypeReductionWithAnyFunctionType.symbols, testdata/baselines/reference/compiler/subtypeReductionWithAnyFunctionType.types, testdata/tests/cases/compiler/subtypeReductionWithAnyFunctionType.ts
=> Make `anyFunctionType` a supertype in strict subtype relation

README.md
Fixes a typo/miswording in the README.
=> Fix typo in README Other Notes section

internal/checker/checker.go, internal/testutil/harnessutil/harnessutil.go, testdata/baselines/reference/compiler/expandoContextualTypes.symbols, testdata/baselines/reference/compiler/expandoContextualTypes.types, testdata/tests/cases/compiler/expandoContextualTypes.tsx
=> Non-circular type resolution for expando assignment declarations

internal/compiler/emitHost.go, internal/compiler/fileloader.go, internal/compiler/program.go, internal/ls/completions.go, internal/project/project.go, internal/testutil/harnessutil/harnessutil.go, internal/testutil/tsbaseline/js_emit_baseline.go
=> Remove unnecessary compilerOptions and use directly from config

internal/transformers/utilities.go, testdata/baselines/reference/submodule/conformance/inlineJsxFactoryDeclarations.js, testdata/baselines/reference/submodule/conformance/inlineJsxFactoryDeclarations.js.diff, testdata/baselines/reference/submodule/conformance/inlineJsxFactoryDeclarationsLocalTypes.js, testdata/baselines/reference/submodule/conformance/inlineJsxFactoryDeclarationsLocalTypes.js.diff
=> fix(949): fix unmatched closing tags in JSX with referenced identifiers

internal/ls/string_completions.go
=> Defer type checker disposal

_packages/api/package.json, _packages/api/src/client.ts, package-lock.json
After https://github.com/microsoft/libsyncrpc/pull/10
=> Move libsyncrpc to new name

testdata/baselines/reference/compiler/subpathImportDeclarationEmit.js, testdata/baselines/reference/compiler/subpathImportDeclarationEmit.symbols, testdata/baselines/reference/compiler/subpathImportDeclarationEmit.types, testdata/tests/cases/compiler/subpathImportDeclarationEmit.ts
Closes #1328
This was fixed by #1336
=> Add regression test for 1328

internal/execute/outputs.go, internal/execute/tsc.go
Report incremental build times
Fixes #1464
=> Add times for changes compute and buildinfo read time

internal/checker/relater.go, testdata/baselines/reference/compiler/typeParameterComparableRelation.errors.txt, testdata/baselines/reference/compiler/typeParameterComparableRelation.symbols, testdata/baselines/reference/compiler/typeParameterComparableRelation.types, testdata/tests/cases/compiler/typeParameterComparableRelation.ts
=> Fix type parameter constraint check in comparable relation

internal/vfs/utilities.go
There's no need to use a regex for this.
=> Don't use a regex in IsImplicitGlob

NOTICE.txt
One day this will be automated...
=> Regenerate NOTICE.txt file

.github/actions/setup-go/action.yml
I typo'd this, so no workflow is restoring the modules ☹️
=> Fix module cache
