- cmd/tsgo/main.go
- internal/binder/binder_test.go
This is getting pointed out enough that it's worth documenting explicitly.
> Clarify double GC

- internal/ast/ast.go
- internal/ast/utilities.go
- internal/checker/checker.go
- internal/checker/utilities.go
- internal/transformers/runtimesyntax.go
- internal/transformers/runtimesyntax_test.go
- internal/transformers/typeeraser.go
This ports emit for parameter property initializers from Strada. Since parameter properties are handled by `RuntimeSyntaxTransformer`, we no longer elide visibility modifiers on constructor parameters in `TypeEraserTransformer`.
> Support emit for parameter property initializers

- internal/ast/ast.go
- internal/ast/utilities.go
- internal/printer/printer.go
- internal/printer/printer_test.go
- internal/transformers/commonjsmodule.go
- internal/transformers/typeeraser.go
This ports `PartiallyEmittedExpression` from Strada to preserve newline emit as a result of type erasure. `PartiallyEmittedExpression` will also eventually be used to preserve source maps and comments, as it does in Strada.
> Add PartiallyEmittedExpression to preserve newlines after type erasure

- internal/transformers/commonjsmodule_test.go
- internal/transformers/runtimesyntax_test.go
- internal/transformers/utilities.go
This amends `isIdentifierReference` to recognize identifiers whose parent is a `TemplateSpan`.
> Recognize identifier reference in template literal

- internal/diagnosticwriter/diagnosticwriter.go
- testdata/baselines/reference/submodule/compiler/deeplyNestedAssignabilityIssue.errors.txt
- testdata/baselines/reference/submodule/compiler/deeplyNestedAssignabilityIssue.errors.txt.diff
- testdata/baselines/reference/submodule/compiler/duplicateIdentifierRelatedSpans2.errors.txt
- testdata/baselines/reference/submodule/compiler/duplicateIdentifierRelatedSpans2.errors.txt.diff
- testdata/baselines/reference/submodule/compiler/duplicateIdentifierRelatedSpans4.errors.txt
- testdata/baselines/reference/submodule/compiler/duplicateIdentifierRelatedSpans4.errors.txt.diff
- testdata/baselines/reference/submodule/compiler/duplicateIdentifierRelatedSpans5.errors.txt
- testdata/baselines/reference/submodule/compiler/duplicateIdentifierRelatedSpans5.errors.txt.diff
- testdata/baselines/reference/submodule/compiler/duplicateIdentifierRelatedSpans6.errors.txt
- testdata/baselines/reference/submodule/compiler/duplicateIdentifierRelatedSpans6.errors.txt.diff
- testdata/baselines/reference/submodule/compiler/duplicateIdentifierRelatedSpans7.errors.txt
- testdata/baselines/reference/submodule/compiler/duplicateIdentifierRelatedSpans7.errors.txt.diff
> Align gutter width with old compiler

- internal/printer/printer.go
- internal/printer/printer_test.go
Strada doesn't currently use `emitEmbeddedStatemen` for `LabeledStatement`, though that would be more consistent with similar statements (`if`, `do`, `while`, etc.). This PR aligns our emit with Strada to reduce spurious diffs in future emit baselines.
> Align LabeledStatement emit with Strada

- cmd/tsgo/enablevtprocessing_other.go
- cmd/tsgo/enablevtprocessing_windows.go
- cmd/tsgo/main.go
Before:
After:
Fixes #480
(I've never used Go before and I didn't verify this works on MacOS or Linux.)
> Enable virtual terminal processing on Windows

- .gitignore
- internal/vfs/osvfs/os.go
On wasm, we can't get the current executable, so the FS will fail for WASI. Just assume case sensitive on `GOARCH=wasm` for now.
That and gitignore `*.wasm` files like we do `*.exe`.
> Fix a couple of small wasm issues

- internal/transformers/commonjsmodule.go
- internal/transformers/commonjsmodule_test.go
This properly sets `.Loc` when transforming a shorthand property assignment during the CJS module transform.
> Preserve trailing comma when rewriting shorthand assignment

- .github/workflows/ci.yml
From Go 1.23, the diff flag was added to go mod tidy, which exits with a non-zero status if there are differences.
I refactored the GitHub Actions workflow to use `go mod tidy -diff`.
cf. [Go 1.23 Release Notes - The Go Programming Language](https://tip.golang.org/doc/go1.23#go-command)
> The new go mod tidy -diff flag causes the command not to modify the files but instead print the necessary changes as a unified diff. It exits with a non-zero code if updates are needed.
> Refactor to use go mod tidy -diff in GitHub Actions

- cmd/tsgo/enablevtprocessing_windows.go
> Update Windows ANSI code code based on feedback

- internal/checker/checker.go
- internal/checker/flow.go
- internal/checker/inference.go
- internal/checker/printer.go
- internal/checker/relater.go
- internal/checker/types.go
- internal/checker/utilities.go
- internal/evaluator/evaluator.go
- internal/jsnum/pseudobigint.go
- internal/transformers/runtimesyntax.go
- internal/transformers/runtimesyntax_test.go
- internal/transformers/utilities.go
This supersedes #229 and extracts `Evaluator` from checker to be reused by the runtime syntax transformer, resulting in emit that more closely aligns with Strada.
> Extract evaluator from checker, more enum emit alignment

- internal/transformers/runtimesyntax.go
- internal/transformers/runtimesyntax_test.go
An addendum to #607, this forces most initialized enum members to use a synthetic node to align with Strada emit for literal values. #607 attempted to preserve the original expression for the purpose of comment emit and preserving quote style, but that turns out to be inconsistent with Strada.
> Always create synthetic enum initializer

- .golangci.yml
Since tenv has been deprecated since golangci-lint v1.64.0, I have replaced it with usetesting.
```
$ hereby lint
> WARN The linter 'tenv' is deprecated (since v1.64.0) due to: Duplicate feature in another linter. Replaced by usetesting. 
```
- [golangci-lint - tenv](https://golangci-lint.run/usage/linters/#tenv)
- [golangci-lint - usetesting](https://golangci-lint.run/usage/linters/#usetesting)
> Replace deprecated tenv with usetesting

- .golangci.yml
The configuration for wrapcheck was left behind even though it was disabled, so I have removed it.
- [Add FS wrapper to correctly emulate case insensitivity in testing #112](https://github.com/microsoft/typescript-go/pull/112)
- The PR disabled wrapcheck.
> Remove unnecessary configurations from .golangci.yml

- internal/tsoptions/tsconfigparsing_test.go
I modified the test code to pass the test case for "handles escaped characters in strings correctly."
- [typescript-go / Tsconfig parsing implementation #207](https://github.com/microsoft/typescript-go/pull/207)
- [TypeScript / handles escaped characters in strings correctly jsonParse.js](https://github.com/microsoft/TypeScript/blob/52c59dbcbee274e523ef39e6c8be1bd5e110c2f1/tests/baselines/reference/config/tsconfigParsing/handles%20escaped%20characters%20in%20strings%20correctly%20jsonParse.js)
> Pass the 'handles escaped characters in strings correctly' test case

- Herebyfile.mjs
This PR improves the JSDoc comment for the `goBuildTags()` function by adding a missing `@returns {string[]}` tag.
- Helps IDEs provide better autocomplete and type inference.
- Improves developer experience, especially when using `// @ts-check`.
- Enhances documentation clarity for future contributors.
> docs: Add missing @returns tag to goBuildTags JSDoc

- _tools/customlint/emptycase.go
- internal/checker/checker.go
- internal/project/service.go
- internal/testutil/testutil.go
Using predefined `any` for empty interface
> chore: change empty interface to using any predefine type

- internal/checker/checker.go
Addresses #609 
The base Typescript implementation of `getObjectTypeInstantiation` includes a mechanism to preemptively cache `CouldContainTypeVariable` when it instantiates a type that it knows can have no type variables. 
The golang implementation is currently missing this optimization, which can trigger different control flow and a higher number of calls to `instantiateAliasedType` than `tsc`, which in turn leads to differing behavior with regard to instantiation depth restrictions.
This PR reintroduces this logic into the golang codebase.
The original Typescript can be found [here](https://github.com/microsoft/TypeScript/blob/52c59dbcbee274e523ef39e6c8be1bd5e110c2f1/src/compiler/checker.ts#L20375)
For simplicity, the relevant code is this:
```ts
const resultObjectFlags = …
```
> Re-introduce preemptive caching of CouldContainTypeVariables

- .golangci.yml
- internal/checker/checker.go
- internal/checker/emitresolver.go
- internal/checker/relater.go
- internal/testutil/jstest/node.go
- internal/transformers/esmodule.go
The PR enables `misspell` linter and fixes up spelling issues.
> Fix misspell lint issues

- internal/vfs/osvfs/os_test.go
Fixes #493
All I need is some path that isn't going to be a symlink. It seems very unlikely that someone will have symlinked their homedir itself.
> Use homedir for realpath test

- internal/compiler/module/cache.go
This reduces alloc/GC churn as append in theory can expand a slice without having to copy the original. Loosely this appears to massively improve performance inside ResolveModuleName. In one example running the LSP locally it drops initialization time from ~90 seconds to ~20 seconds.
I believe this is still safe given the usage of mutex's, but also my understanding of go threading is not the best, so if this isn't safe lemme know. But it appears to be fine both locally and in the test suite.
**Before**
**After**
> perf: use append instead of Concat in appendLookupLocations

- internal/compiler/program.go
Deduplicates unsupported extensions. Currently, running `tsgo` in a large project results in a massive warning message:
```
Warning: The project contains unsupported file types (.tsx, .tsx, .tsx, .tsx, .tsx, .tsx, .tsx, .tsx, .tsx, .tsx, .tsx, .tsx, .tsx, .tsx, .tsx, .tsx, .tsx, .tsx, .tsx, .tsx, .tsx, .tsx, .tsx, .tsx, .tsx, .tsx, .tsx, .tsx, .tsx, .tsx, .tsx, .tsx, .tsx, .tsx, .tsx, .tsx, .tsx, .tsx, .tsx, .tsx, .tsx, .tsx, ..., .js, .mjs), which are currently not fully type-checked.
```
This makes the message shorter:
```
Warning: The project contains unsupported file types (.tsx, .js, .mjs), which are currently not fully type-checked.
```
> Deduplicate unchecked extensions on warning message

- internal/checker/checker.go
- testdata/baselines/reference/submodule/compiler/expressionWithJSDocTypeArguments.types
- testdata/baselines/reference/submodule/compiler/expressionWithJSDocTypeArguments.types.diff
- testdata/baselines/reference/submodule/compiler/parseInvalidNonNullableTypes.errors.txt
- testdata/baselines/reference/submodule/compiler/parseInvalidNonNullableTypes.errors.txt.diff
- testdata/baselines/reference/submodule/compiler/parseInvalidNonNullableTypes.types
- testdata/baselines/reference/submodule/compiler/parseInvalidNonNullableTypes.types.diff
- testdata/baselines/reference/submodule/compiler/parseInvalidNullableTypes.errors.txt
- testdata/baselines/reference/submodule/compiler/parseInvalidNullableTypes.errors.txt.diff
- testdata/baselines/reference/submodule/compiler/parseInvalidNullableTypes.types
- testdata/baselines/reference/submodule/compiler/parseInvalidNullableTypes.types.diff
- testdata/baselines/reference/submodule/conformance/jsdocDisallowedInTypescript.types
- testdata/baselines/reference/submodule/conformance/jsdocDisallowedInTypescript.types.diff
Type checks the JSDoc types
- `* = any`
- `!T = T`
- `?T = T | null`
- `...T = T[]`
- `T= = T | undefined`
Only improves a few TS tests since I don't have `@param` or `@type` contributing type annotations in JS.
The rules for JSVariadicType (`...T`) are simplified: it's now always a synonym for `T[]`. Previously it was only `T[]` when used correctly: as a rest parameter, and was `T | undefined` otherwise.
This makes no sense.
And it turns out that signature help in Strada has always used the simpler `...T = T[]` rule anyway, so that's what JS users are used to seeing as long as they don't have checkJs turned on. What `...` is still used is in random JS code that is going to be mostly viewed rather than edited, so a simplification is overdue.
> Check JSDoc types

- Herebyfile.mjs
We've discovered that the go test cache makes `go test ./internal/testrunner` 4-5x slower on Windows:
```console
$ go clean -testcache
$ Measure-Command { go test ./internal/testrunner | Out-Default }
ok      github.com/microsoft/typescript-go/internal/testrunner  13.584s
Days              : 0
Hours             : 0
Minutes           : 1
Seconds           : 5
Milliseconds      : 364
Ticks             : 653649277
TotalDays         : 0.000756538515046296
TotalHours        : 0.0181569243611111
TotalMinutes      : 1.08941546166667
TotalSeconds      : 65.3649277
TotalMilliseconds : 65364.9277
```
```console
$ Measure-Command { go test -count=1 ./internal/testrunner | Out-Default }
ok      github.com/microsoft/typescript-go/internal/testrunner  11.726s
Days              : 0
Hours             : 0 …
```
> Disable test caching on Windows, hide gotestsum skipped tests outside CI

- internal/ast/utilities.go
The rest of the usages were positive `ImpliedNodeFormat == something` checks which is fine
> Fix nil sourcefilemetadata case in `GetImpliedNodeFormatForEmitWorker`

- .custom-gcl.yml
- .golangci.yml
- Herebyfile.mjs
Notable changes:
- `gosimple`/`stylecheck`/`staticcheck` were all merged into a single `staticcheck` linter, so I disabled that for now since we're not ready to enable it.
- Most flags / timeouts we set are now the defaults, so they go away.
- I disabled the `whitespace` linter, which is surprisingly slow (not new).
> Update to golangci-lint v2

- internal/tsoptions/tsconfigparsing.go
- Removed unnecessary blank line to make function documentation visible on hover.
- No changes to logic or functionality.
> fix(docs): Ensure function documentation appears on hover

- internal/tspath/path_test.go
`b.Loop` shouldn't itself be called multiple times. Invert this test loop.
> Fix BenchmarkGetNormalizedAbsolutePath

- .github/workflows/ci.yml
- Herebyfile.mjs
The coverage we list is wrong because I forgot that we pass coverage flags to multiple different tests, so whichever runs last ends up winning. Oops.
> Ensure coverage data from multiple tasks don't overwrite each other

- README.md
Marking this as "done", where "done" is defined in the readme as "should work modulo bugs, and it's okay to report bugs".
> Mark JSX as done in the readme

- README.md
Was noticing this list is kinda hard to parse as-is
> Convert status overview to a table

- internal/collections/syncmap.go
- internal/project/documentregistry.go
- internal/testutil/harnessutil/harnessutil.go
- internal/vfs/cachedvfs/cachedvfs.go
I think there's a proposal to add this exact type to the stdlib eventually, but I'm finding it increasingly annoying to deal with `any` when making new `sync.Map`s.
> Add typesafe sync.Map wrapper

- internal/checker/checker.go
- internal/compiler/program.go
Combo of #752 and a fix to the race by @ahejlsberg.
> Create checkers in parallel, fix race on parents

- internal/ast/precedence.go
- internal/printer/printer.go
This is needed to avoid a panic in a test once CommonJS import/exports are available.
I've guessed at the right thing to do here but I don't have a solid idea.
I haven't added tests because I'm not sure how:
- Submodule tests only cover `*`
- `*`, `!T` and `?T` are testable outside JSDoc.
- `...T` and `T=` are only parsed in JSDoc.
> Add precedence and printing for JSDoc types

- internal/binder/binder.go
- internal/binder/binder_test.go
- internal/compiler/program.go
- internal/core/compileroptions.go
- internal/printer/namegenerator_test.go
- internal/project/documentregistry.go
- internal/project/service_test.go
- internal/testutil/harnessutil/harnessutil.go
- internal/transformers/commonjsmodule_test.go
- internal/transformers/esmodule_test.go
- internal/transformers/importelision_test.go
- internal/transformers/runtimesyntax_test.go
This PR makes `SourceFileAffectingCompilerOptions` consist of only _fully computed_ values (in prep for some other changes).
- We can now prove that the binder (and in the future, parser) only touch things that they need.
- The values can be computed once and reused.
- `SourceFileAffectingCompilerOptions` is smaller, allowing much more AST reuse.
The AST reuse results in the tests running 20-25% faster, and using 1GB less peak memory.
psrecord before:
psrecord after:
Before, it's maybe 8GB, before maybe 7GB.
> Make SourceFileAffectingCompilerOptions hold fully computed values, use in binder

- .github/workflows/ci.yml
Want to verify that #742 is going to be correct, since formatting changes there seem dubious.
> Check that LSP code gen is correct in CI

- internal/execute/watcher.go
fixes #778
cc @iisaduan @jakebailey
> Fix some bugs in `tsc -w`

- internal/lsp/lsproto/_generate/fetchModel.mjs
- internal/lsp/lsproto/_generate/metaModelSchema.mts
- package-lock.json
- package.json
When I wrote the code for the LSP code generator, I didn't realize there was already an existing set of type declarations for the meta model. Just pull that instead of using a declaration file generator.
> Remove JSON schema generator in favor of upstream metaModel.ts

- internal/astnav/tokens.go
- internal/astnav/tokens_test.go
- testdata/baselines/reference/astnav/FindPrecedingToken.mapCode.ts.baseline.txt
The new code ports the original `findPrecedingToken` as faithfully as possible.
From the baselines, there are two differences:
1. The range of some returned tokens is different in Corsa.
2. In Strada, when the position is inside a JSDoc comment that has no tags, `findPrecedingToken` returns `undefined`. In Corsa, right now, we return the JSDoc. I am not sure if this difference matters or how to properly deal with that, so I thought I should leave this as a future work item.
> Add `findPrecedingToken`

- internal/parser/jsdoc.go
Just a drive-by change. I'm not sure if the compiler is "smart enough" to get rid of the allocation, but it felt better to be more explicit anyway.
> Remove possible allocation of `NodeList` by eliminating `IfElse`.

- internal/ast/ast.go
- internal/checker/flow.go
Fix typo in comments ("conditonal" → "conditional", "pesudo" → "pseudo")
> Fix minor typo

- internal/astnav/tokens.go
- internal/astnav/tokens_test.go
Turns out, for `findPrecedingToken`/`findRightmostValidToken`, we have to look at every token that is not part of the AST and that occurs between "empty" AST nodes.
A simplified illustration of the problem present in the test I added:
```ts
variable.|
function foo() { ... }
```
With position at `|`, we should return the dot token, because it is the rightmost valid (non-empty) token that precedes the position.
But to find it, we have to look at tokens that occur between the identifier node `variable`, and the empty identifier node that the parser adds after the dot to construct a valid property access expression.
Before this PR, we were only looking at tokens after the last visited node, i.e. after the empty identifier node.
Now, we look at every token that occurs in between visited nodes, …
> Fix `findRightmostValidToken`

- internal/ls/converters.go
Fixes issue with errant `A` characters inserted into file paths when using language service on Windows.
> Fix URI un-escaping on Windows

- cmd/tsgo/main.go
This is helpful for us who are testing nightlies to be able to work backwards to figure out where regressions happened
`built/local/tsgo -version`
yields
`tsgo commit d851a61fc472fd4e50f0d23b84bd6f102bec3a6e`
> Add `-version` to CLI

- internal/parser/parser.go
These are no longer needed, given `putParser` clears everything out.
> Remove old parser clears

- internal/astnav/tokens.go
- internal/astnav/tokens_test.go
We shouldn't look beyond the current node end position when looking for trailing tokens. I was missing an update to the end position in recursive calls to `find`.
> Update end position in `findRightmostValidToken`

- internal/tsoptions/parsinghelpers.go
- internal/tsoptions/parsinghelpers_test.go
This mucks with the real code a bit, but it works better and is simpler.
@jakebailey FYI, and I swear I'm done bugging you 😝 
See https://github.com/microsoft/typescript-go/pull/839 https://github.com/microsoft/typescript-go/issues/842
> Improve the missing CompilerOptions check

- internal/binder/binder_test.go
- internal/core/compileroptions.go
- internal/transformers/commonjsmodule_test.go
- internal/transformers/esmodule.go
- internal/transformers/esmodule_test.go
- internal/tsoptions/decls_test.go
- internal/tsoptions/parsinghelpers.go
- internal/tsoptions/tsconfigparsing_test.go
- testdata/baselines/reference/config/tsconfigParsing/parses tsconfig with compilerOptions, files, include, and exclude with json api.js
- testdata/baselines/reference/config/tsconfigParsing/parses tsconfig with compilerOptions, files, include, and exclude with jsonSourceFile api.js
- testdata/baselines/reference/tsc/commandLine/Parse-enum-type-options.js
Following from #853.
I'm not sure whether or not `ModuleKind` was intended but I assume not?
> Further test and fix compiler options

- cmd/tsgo/main.go
- internal/ast/ast.go
- internal/checker/checker.go
- internal/checker/checker_test.go
- internal/checker/utilities.go
- internal/compiler/program.go
- internal/execute/tsc.go
- internal/ls/diagnostics.go
- internal/testutil/harnessutil/harnessutil.go
With this PR the `CheckSourceFile` and `GetDiagnostics` methods on `Checker` and `GetSyntacticDiagnostics`, `GetBindDiagnostics`, and `GetSemanticDiagnostics` on `Program` support cancellation through a `context.Context` which is passed as the first parameter to those methods.
When an operation is cancelled, any subsequent call to `CheckSourceFile`, `GetDiagnostics`, `GetDiagnosticsWithoutCheck`, or `GetGlobalDiagnostics` on that checker will panic regardless of which context the checker is invoked on. (Following cancellation, a checker contains only a partial list of diagnostics, and without more extensive work to track which source elements were checked and which weren't, that checker can no longer deliver a consistent set of diagnostics.)
> Support cancellation in checker

- internal/ast/ast.go
The missing `visit(v, node.Expression)` caused a crash in the language service for a type parameter with an incomplete `extends` clause.
> Properly visit the `Expression` node of a `TypeParameterDeclaration`

- internal/checker/printer.go
This PR fixes logic for choosing value/type meanings in quick info that wasn't quite working correctly. We now show the right meaning when hovering on each of the identifiers in this code:
```ts
enum E {
A = 1,
B = "hello",
C = Math.sqrt(2)
}
interface Thing {
bar: number
}
declare const Thing: () => Thing
let t1: typeof Thing = Thing
let t2: Thing = Thing()
Thing().bar
declare function strange<T>(T: T): T;
```
> Improve logic for choosing value/type meanings in quick info

- internal/vfs/osvfs/realpath_test.go
- internal/vfs/osvfs/realpath_windows.go
My hand-written `open` function doesn't handle long paths, relying on the SEH bit Go normally sets. But, that bit is undocumented and seemingly isn't approved for using in releases, and isn't set in artifacts built by the Go fork used by Microsoft.
Rather than use `CreateFile` directly, use `os.Open` instead, which will handle long paths. I didn't do this initially because I thought it didn't work on directories, but it actually has worked since https://go.dev/cl/405275 a long time ago.
I don't have a test for this because I can't seem to make a link with long enough paths in the tests... ☹️ 
cc @qmuntal
> Use os.Open for Windows realpath to handle long paths

- internal/checker/services.go
- internal/ls/completions.go
- internal/ls/completions_test.go
- internal/scanner/scanner.go
- internal/scanner/utilities.go
Fill in the JSX-related places in completions.
Follow-up of #858.
> JSX completions

- internal/compiler/program.go
- internal/project/project.go
This PR introduces a fast path for program updates in the language service. When only a single file has been modified and none of the changes impact the program's structure, we create a new program by just cloning the existing program and replacing the single file. This dramatically improves responsiveness in the typical path of typing in a file.
> Introduce fast path for program updates in language service

- internal/parser/jsdoc.go
- testdata/baselines/reference/conformance/jsdocParseAwait.errors.txt
- testdata/baselines/reference/conformance/jsdocParseAwait.symbols
- testdata/baselines/reference/conformance/jsdocParseAwait.types
- testdata/tests/cases/conformance/jsdoc/jsdocParseAwait.ts
Fixes #874
---
`parseJSDocIdentifierName` uses `newIdentifier`, which may flag `await` identifier as a top-level declaration. @sandersn should this be suppressed when parsing JSDoc?
https://github.com/microsoft/typescript-go/blob/cab7a0bf793f3ba0e83619798f2eb191673fe4c7/internal/parser/jsdoc.go#L1253
https://github.com/microsoft/typescript-go/blob/cab7a0bf793f3ba0e83619798f2eb191673fe4c7/internal/parser/parser.go#L2860-L2867
> fix: avoid treating await in jsdoc as top-level await

- internal/project/project.go
- internal/project/service.go
- internal/project/service_test.go
Fixes a bug caught by @gabritto in https://github.com/microsoft/typescript-go/pull/879/files/a30a84c490a5d49555a8f46b1516836b75c560e8#r2098483287.
I had to make the other changes in order to make the test fail; there was an unnecessary double update on config file changes that was clearing out the dirty state on the second update.
> Unconditionally set dirtyFilePath in markAsDirty

- internal/ls/completions_test.go
- internal/project/service.go
- internal/testutil/lstestutil/lstestutil.go
Taken from a TSServer config message, replacing `allowSyntheticDefaultImports` with `esModuleInterop`
> Copy default compiler options for inferred projects from VS Code client

- .vscode/launch.template.json
- internal/testrunner/compiler_runner.go
I imagine this is a useful launch task/flag for tracing slow tests - basically just pulled from the `go` docs.
> Add option to launch test with pprof profiling enabled

- _build/azure-pipelines.compliance.yml
> Add compliance pipeline

- internal/project/documentregistry.go
- internal/project/project.go
- internal/project/scriptinfo.go
- internal/project/service.go
Changes `project` to operate with a single mutex, and avoids reading `scriptInfo.Version()` multiple times during parsing.
> [LSP] Fix data races on dirty state and script info version

- _build/azure-pipelines.compliance.yml
This one actually does what I want now. Just run CG; it has populated it correctly for this branch in testing.
For some reason, the 1ESPT template disables all CG. Not sure why.
> Fix compliance pipeline take two

- internal/binder/binder.go
- internal/core/pattern.go
- testdata/baselines/reference/compiler/invalidGlobalAugmentation.errors.txt
- testdata/tests/cases/compiler/invalidGlobalAugmentation.ts
Fixes #870
~~Global augmentations are stored as pattern ambient modules with zeroed patterns.~~ Invalid global augmentations were falling through binder cases and getting put into pattern ambient modules, when they should have been skipped.
> Check patterns for validity before putting them into pattern ambient modules

- internal/execute/system.go
- internal/execute/tsc.go
- testdata/baselines/reference/tsc/noEmit/when-project-has-strict-true.js
This turns off the early exit and error for `--incremental`; I think it's fine to just let compilation proceed in this case.
Fixes #906
> Don't error on --incremental, just run normally

- internal/checker/services.go
> Fix GetRootSymbols missing return

- internal/execute/tsc.go
This is a bit less cryptic than "error TS6369: Option '--build' must be the first command line argument.", which only shows up because we don't yet have build mode code that checks the first arg.
> Error early on --build

- internal/ast/utilities.go
- internal/checker/checker.go
- internal/checker/utilities.go
- internal/parser/reparser.go
- testdata/baselines/reference/conformance/deepElementAccessExpressionInJS.errors.txt
- testdata/baselines/reference/conformance/deepElementAccessExpressionInJS.symbols
- testdata/baselines/reference/conformance/deepElementAccessExpressionInJS.types
- testdata/tests/cases/conformance/salsa/deepElementAccessExpressionInJS.ts
Fixes #890
There were two related functions but only one caller needed the .Text() followup. The new code is stricter and therefore less likely to panic downstream.
There was also a duplicate implementation of IsModuleExports in checker. I removed that and cleaned it up as well.
This is also the inauguaral test in cases/conformance/salsa.
> Clean up GetElementOrPropertyAccessName

- internal/lsp/lsproto/_generate/fetchModel.mjs
- internal/lsp/lsproto/lsp_generated.go
This is the one type that is has an unexported name in the spec.
> Rename _InitializeParams type in LSP

- internal/ast/diagnostic.go
- internal/checker/checker.go
- internal/compiler/program.go
- internal/ls/diagnostics.go
> Expose bind diags in LSP, show dead/deprecated code

- internal/checker/checker_test.go
- internal/compiler/program.go
- internal/compiler/program_test.go
- internal/execute/tsc.go
- internal/execute/watcher.go
- internal/tsoptions/commandlineparser.go
- internal/tsoptions/tsconfigparsing.go
- internal/tsoptions/utilities.go
This is from back when the CLI was hacked-up. Now there's no reason to have it.
> Eliminate ProgramOptions.ConfigFileName

- internal/checker/checker.go
- internal/checker/printer.go
- internal/checker/relater.go
- internal/checker/symbolaccessibility.go
- internal/ls/hover.go
- internal/printer/singlelinestringwriter.go
The writing and clearing and passing down of things doesn't seem to be working; for now just flip this all to use the returned string until we can do something faster. (I'm not doing something faster because some of the code does some truncation that is not easily doable via streaming.)
Also the unknown symbol flip.
> Fix up hover code, mostly temporary

- Herebyfile.mjs
Fixes #990
I guess VS Code won't fall back on the linux VSIX. Just build two more (which are copies of the linux one).
Also in this PR are changes to make `Herebyfile.mjs` happy in the native preview LSP.
> Generate alpine VSIXs

- .vscode/tasks.json
- package.json
Speeds up local dev and allows attaching when using this flow.
> Build tsgo with debug tasks when launching extension locally

- internal/vfs/utilities.go
quick explanation: 
Absolute paths like "/some/path/glob/**" were getting through when the correct path would be "/some/path/glob"
long: 
An include like `../../ambient-types/**/*` is turned into an absolute path, let's say `/home/dev/project/ambient-types/**/*` and passed here https://github.com/microsoft/typescript-go/blob/e8d352c89b733779275a364d6e5de7df65ac9a42/internal/vfs/utilities.go#L241-L252
That strips the last chunk of the path, so returns `/home/dev/project/ambient-types/**`.  Then `patterns` in https://github.com/microsoft/typescript-go/blob/e8d352c89b733779275a364d6e5de7df65ac9a42/internal/vfs/utilities.go#L425 ends up with one of it's base paths as  `/home/dev/project/ambient-types/**` and that is not a valid path to visit in …
> Strip glob patterns from include basePath

- internal/checker/checker.go
- internal/collections/ordered_map.go
- internal/tsoptions/tsconfigparsing.go
Fixes #978
#978 broke because `removeWildcardFilesWithLowerPriorityExtension` passed the map by value and then attempted to delete from it. That will cause the internal `map` to be modified, but the `key` slice to _not_ be modified in the caller. The fix is to pass by pointer.
To prevent this bug from happening in the future, use the `noCopy` pattern to make `go vet` check it. This reveals another place we weren't passing the map by pointer. That one's not a bug, but it could have been.
I don't have a real test for the problem as I think it's self explanatory and `go vet` will catch this, but I could figure out how to test it if required.
> Ensure we don't copy OrderedMaps

- README.md
Follow up to update the README now that #791 is merged!
I tried to write notes based on the TODOs in the PR but please correct me if I’m misrepresenting the status of this feature.
> Update “Declaration emit” in README progress table

- internal/project/watch.go
I realized after the fact that `getDirectoryToWatchFailedLookupLocation` doesn't really care about the actual _contents_ of the path, just how the parts split apart and where `node_modules` is. This means that passing in `/foo/node_modules/bar/index.js` and `/foo/node_modules/bar/blah.js` will return identical results.
Prevent the expensive call to `getDirectoryToWatchFailedLookupLocation` by only doing it once per dirname.
In my testing, this halves the amount of time spent mapping paths to globs. From:
```
Info 9    [11:42:17.604] createGlobMapper took 86.409653ms to create 3 globs for 31663 failed lookups
Info 10   [11:42:17.739] failed lookup watches updated watcher-1:
/home/jabaile/work/node_modules/**/*.{js,jsx,mjs,cjs,ts,tsx,mts,cts,json} …
```
> Skip more work when creating LSP watch globs

- internal/project/ata.go
- internal/project/discovertypings.go
- internal/project/project.go
Noticed these while looking at the ATA code.
`Compact` was used in a couple of places where it should have been `Clone` (so ended up modifying input slice later), and one `Compact` call was missing a sort.
Additionally, we could leak memory out of ATA due to the pending requests; it's possible that it would be cleared eventually, but it's best to zero out an element of a slice before slicing it off.
> Fix a couple of Project/ATA bugs

- internal/checker/checker.go
ports https://github.com/microsoft/TypeScript/pull/60358
> Port "Fixed a JSDoc-related crash when obtaining type of a type literal type argument"

- internal/checker/flow.go
- testdata/baselines/reference/submodule/compiler/inferTypePredicates.errors.txt
- testdata/baselines/reference/submodule/compiler/inferTypePredicates.errors.txt.diff
- testdata/baselines/reference/submodule/compiler/inferTypePredicates.js
- testdata/baselines/reference/submodule/compiler/inferTypePredicates.js.diff
- testdata/baselines/reference/submodule/compiler/inferTypePredicates.types
- testdata/baselines/reference/submodule/compiler/inferTypePredicates.types.diff
ports https://github.com/microsoft/TypeScript/pull/60782
> Port "Narrow types by satisfies expressions"

- internal/ast/utilities.go
- internal/binder/binder.go
- internal/parser/references.go
- testdata/baselines/reference/submodule/conformance/importTag17.errors.txt
- testdata/baselines/reference/submoduleAccepted/conformance/importTag17.errors.txt.diff
#970 was incomplete because I misread `SetParentsInChildren` as not setting the parent if the node already has one.
> Fix more parent races

- internal/parser/jsdoc.go
ports https://github.com/microsoft/TypeScript/pull/60640
> Port "fix(60592): JSDoc implements space sensetive"

- cmd/tsgo/sys.go
- internal/execute/outputs.go
- internal/execute/system.go
- internal/execute/testsys_test.go
- internal/execute/tsc.go
In Strada, I can't tell if this time was omitted or just a part of the parse time (probably the latter). But we were totally omitting it in this repo, which hides the fact that config loading and file scanning takes a significant amount of time. Collect this number, and then ensure the total time actually includes everything. 
See: https://github.com/microsoft/typescript-go/issues/1062#issuecomment-2944885778
```
Config time:      0.120s
Parse time:       0.513s
Bind time:        0.100s
Check time:       5.719s
Emit time:        0.721s
Total time:       7.176s
```
This is going to make our total time stat longer, but it's more realistic, and we should totally go and optimize file scanning/matching to eliminate the use of `regexp2`.
As part of this, I've refactored `System` such that time …
> Measure config parse / file scan time, actual total time

- internal/checker/flow.go
- testdata/baselines/reference/compiler/exhaustiveSwitchStatementsGeneric1.symbols
- testdata/baselines/reference/compiler/exhaustiveSwitchStatementsGeneric1.types
- testdata/tests/cases/compiler/exhaustiveSwitchStatementsGeneric1.ts
ports https://github.com/microsoft/TypeScript/pull/60644
fixes https://github.com/microsoft/typescript-go/issues/986
> Port "Check if switch statements are exhaustive when their expressions is generic with a literal type constraint"

- internal/lsp/server.go
Sort of pulled out of #991, but I'm hoping this helps people who are seeing their `tsgo` processes not exit.
The next measure we could take is to watch the parent process (PID is given during init) and exit if it exits.
> Ensure LSP readLoop doesn't block shutdown

- .dprint.jsonc
- internal/api/server.go
- internal/ast/kind.go
- internal/checker/types.go
- internal/core/compileroptions.go
- internal/core/compileroptions_stringer_generated.go
- internal/core/languagevariant.go
- internal/core/scriptkind.go
- internal/core/tristate.go
- internal/diagnostics/diagnostics.go
- internal/diagnostics/diagnostics_generated.go
- internal/diagnostics/generate.go
- internal/lsp/lsproto/_generate/generate.mjs
- internal/lsp/lsproto/lsp_generated.go
- internal/project/project.go
- internal/testutil/projecttestutil/clientmock_generated.go
- internal/testutil/projecttestutil/projecttestutil.go
- internal/vfs/vfs.go
- internal/vfs/vfsmock/mock_generated.go
https://github.com/golang/go/issues/73959 will cause gopls to format generated files, which will probably get annoying when browsing around and (accidentally) hitting save, especially given we use gofumpt and not gofmt.
Preemptively format all of our generated files.
> Format all generated files

- internal/checker/emitresolver.go
- internal/checker/nodebuilderimpl.go
> Fix data race via RequiresAddingImplicitUndefined

- .github/workflows/ci.yml
There's no real need to do this; we have no code that's gated by `//go:build darwin` or similar. We do need to check against Linux, Windows, and `noembed`, though.
Dropping this mainly to get rid of one more job that depends on the very limited macOS runner pool.
> Don't lint on macOS in CI

- internal/ast/ast.go
- internal/binder/binder.go
> Remove unused JSGlobalAugmentations

- internal/lsp/server.go
```
WARNING: DATA RACE
Read at 0x00c000232a50 by goroutine 1006:
github.com/microsoft/typescript-go/internal/lsp.(*Server).sendRequest()
/home/jabaile/work/TypeScript-go/internal/lsp/server.go:402 +0x91
github.com/microsoft/typescript-go/internal/lsp.(*Server).WatchFiles()
/home/jabaile/work/TypeScript-go/internal/lsp/server.go:198 +0x36c
github.com/microsoft/typescript-go/internal/project.(*watchedFiles[go.shape.[]string]).update()
/home/jabaile/work/TypeScript-go/internal/project/watch.go:85 +0xbc1
github.com/microsoft/typescript-go/internal/project.(*ConfigFileRegistry).updateRootFilesWatch()
/home/jabaile/work/TypeScript-go/internal/project/configfileregistry.go:134 +0x990
github.com/microsoft/typescript-go/internal/project.(*ConfigFileRegistry).AcquireConfig() …
```
> Generate LSP request IDs atomically

- internal/compiler/fileloader.go
- internal/compiler/program.go
- internal/core/compileroptions.go
- internal/tsoptions/commandlineparser_test.go
- internal/tsoptions/tsconfigparsing_test.go
Enabled by #1106, we can now cache the SourceFileAffecting function's results on the CompilerOptions struct itself.
> Cache CompilerOptions.SourceFileAffecting

- internal/ls/converters.go
- internal/ls/converters_test.go
This more closely mirrors what VS Code did to fix up paths for tsserver.
Fixes #1096
> Fix handling of non-file URIs

- internal/project/checkerpool.go
This call was the only part of the `CheckerPool` interface implementation that were missing the lock.
Fixes #1168
Could fix the other races (since racy code is UB)
> Ensure pool mutex is locked in GetAllCheckers

- internal/checker/grammarchecks.go
- testdata/baselines/reference/conformance/jsdocClassNoTags.js
- testdata/baselines/reference/conformance/jsdocClassNoTags.symbols
- testdata/baselines/reference/conformance/jsdocClassNoTags.types
- testdata/tests/cases/conformance/jsdoc/jsdocClassNoTags.ts
Iterating JSDoc.Tags.Nodes panics if there are no tags. You can iterate nil but not a slice on something that is nil. Expect to see more panics like this on any new code, because we're not tracking nil in the type system anymore.
Fixes #1171
> Fix nil panic on heritage clause in grammar checks

- internal/collections/syncset.go
- internal/lsp/server.go
Fixes #1163
No need for a mutex here, a `SyncSet` and atomics are correct for this given watchers are increasing and unique.
> Fix file watcher data race

- internal/fourslash/test_parser.go
- internal/testrunner/test_case_parser.go
In strada's fourslash, tests would exit immediately if fourslash parsing failed. This PR adds an error + early exit for fourslash tests
Follow up to #1175.
> add error handling to fourslash parsing

- internal/compiler/fileloader.go
- internal/compiler/program.go
- internal/compiler/projectreferencefilemapper.go
- internal/compiler/projectreferenceparsetask.go
- internal/project/configfileregistry.go
- internal/project/defaultprojectfinder.go
- internal/project/defaultprojectfinder_test.go
- internal/project/project.go
- internal/project/projectreferencesprogram_test.go
- internal/project/service.go
- internal/tsoptions/parsedcommandline.go
- Adds loading config to check if the project can be default configured project by matching file names instead of creating project if its composite otherwise creates the project to check
- Looks into referenced projects to find default if the found tsconfig cannot be default project
- Looks into parent folder's tsconfig.json if default not found in the first found tsconfig and its references
> Port finding default project finder code

- internal/checker/exports.go
- internal/checker/nodebuilderimpl.go
- internal/ls/hover.go
- internal/printer/printer.go
Improvements include:
* Show dotted names for members of classes and interfaces.
* Show the resolved overload in calls to overloaded functions and methods.
* Include type arguments in quick info for calls to generic functions and methods.
> Multiple improvements to Quick Info

- internal/checker/checker.go
With crash:
```
panic handling request textDocument/hover interface conversion: ast.nodeData is *ast.ExportDeclaration, not *ast.ImportDeclaration goroutine 24183 [running]:
runtime/debug.Stack()
runtime/debug/stack.go:26 +0x64
github.com/microsoft/typescript-go/internal/lsp.(*Server).dispatchLoop.func1.1()
github.com/microsoft/typescript-go/internal/lsp/server.go:359 +0x50
panic({0x102716c80?, 0x1400fb66210?})
runtime/panic.go:792 +0x124
github.com/microsoft/typescript-go/internal/ast.(*Node).AsImportDeclaration(...)
github.com/microsoft/typescript-go/internal/ast/ast.go:1188
github.com/microsoft/typescript-go/internal/checker.(*Checker).getSymbolAtLocation(0x1404be39008, 0x1400052a120, 0x1)
github.com/microsoft/typescript-go/internal/checker/checker.go:30048 +0xa84 …
```
> Fix getSymbolAtLocation crash on export declaration

- internal/repo/paths.go
- internal/vfs/internal/internal.go
- internal/vfs/vfs_test.go
I don't like unsafe, but in this case I believe it to be reasonable.
When reading from a filesystem, the returned bytes must necessarily never be touched by the underlying filesystem ever again. Otherwise, the caller would experience data races or be unable to modify the data. This means that in effect, the FS is guaranteed to no longer "own" that data, and the caller can do whatever it wants with it.
Our FS abstraction works with strings, but the underlying FSs all provide `[]byte`. Given the above, we can skip the typical `string` to `[]byte` copy and "safely" use `unsafe.String` to directly convert it.
This nets about a 50% improvement in time and memory allocation on non-trivial files. It's not much, but for larger files like `checker.ts`, it means going from a 1 ms read to a 0.5 ms …
> Convert read file content directly to strings

- internal/compiler/fileloader.go
- internal/compiler/parsetask.go
- internal/compiler/program.go
- internal/module/types.go
- internal/project/project.go
Pulling out watching type refs and handling auto type refs change from #1217
> Watch type reference locations too and handle auto type refs

- internal/ls/completions.go
Port the fixes from https://github.com/microsoft/TypeScript/pull/61928.
This fixes a completions unit test that is failing in another branch that I have, and I'm not sure why that test wasn't failing before, probably another bug in astnav code was somehow making it work.
> Port completion fixes for JSX scanning

- .github/workflows/copilot-setup-steps.yml
If this isn't done, runs will fail because the network blocks these requests for the Wasm blobs.
> Run dprint in copilot-setup-steps to prevent network blocking error

- internal/api/encoder/encoder.go
- internal/ast/ast.go
- internal/core/pool.go
- internal/ls/hover.go
- internal/parser/jsdoc.go
- internal/parser/parser.go
One of the largest allocators when parsing code for the editor is JSDoc parsing. By deferring JSDoc part joining until `Text()` is called, we can save a bunch of memory allocations, and make parsing out the DOM types ~5% faster.
```
goos: linux
goarch: amd64
pkg: github.com/microsoft/typescript-go/internal/parser
cpu: Intel(R) Core(TM) i9-10900K CPU @ 3.70GHz
│   old.txt   │              new.txt               │
│   sec/op    │   sec/op     vs base               │
Parse/empty.ts/tsc-20                                          527.5n ± 4%   523.9n ± 1%       ~ (p=0.072 n=10)
Parse/empty.ts/server-20                                       524.1n ± 1%   527.3n ± 1%       ~ (p=0.138 n=10)
Parse/checker.ts/tsc-20                                        48.66m ± 2%   47.70m ± 1%  -1.97% (p=0.002 …
```
> Do less allocation in JSDoc parsing

- internal/ast/ast.go
I looked at the top allocators again; pooling a few more nodes speeds up parsing the DOM types by 3%, reducing allocations in the DOM types by some 50% in the best case.
```
goos: linux
goarch: amd64
pkg: github.com/microsoft/typescript-go/internal/parser
cpu: Intel(R) Core(TM) i9-10900K CPU @ 3.70GHz
│   old.txt   │              new.txt               │
│   sec/op    │   sec/op     vs base               │
Parse/empty.ts/tsc-20                                          527.5n ± 4%   524.1n ± 2%       ~ (p=0.190 n=10)
Parse/empty.ts/server-20                                       524.1n ± 1%   527.3n ± 1%       ~ (p=0.118 n=10)
Parse/checker.ts/tsc-20                                        48.66m ± 2%   47.70m ± 3%       ~ (p=0.063 n=10)
Parse/checker.ts/server-20 …
```
> Pool more top nodes

- internal/compiler/emitter.go
- internal/printer/emitcontext.go
- internal/testutil/tsbaseline/type_symbol_baseline.go
These objects can be reused, which is good because we create one of them per file to emit.
> Pool EmitContext

- internal/checker/inference.go
- testdata/baselines/reference/compiler/strictBestCommonSupertype.symbols
- testdata/baselines/reference/compiler/strictBestCommonSupertype.types
- testdata/tests/cases/compiler/strictBestCommonSupertype.ts
This is a port of https://github.com/microsoft/TypeScript/pull/61903.
Fixes #1222.
> Use strict subtype relation in `getCommonSupertype`

- internal/checker/checker.go
- internal/checker/nodebuilderimpl.go
- internal/checker/symbolaccessibility.go
- internal/compiler/emitHost.go
- internal/compiler/emitter.go
- internal/compiler/program.go
- internal/printer/emithost.go
- internal/testutil/baseline/baseline.go
- internal/testutil/tsbaseline/js_emit_baseline.go
- internal/transformers/tstransforms/importelision_test.go
Present, but commented out, these tests are important to have on as I port emit features, as they point out places where the `EmitResolver` fails to lazily calculate things emit needs. I'm also removing the eager-diagnostics behavior from emit resolver construction entirely. With emit often happening on many separate threads, it is basically never a good idea to require an emit resolver generate diagnostics - right now we lock on a single checker across emit threads, but we can and probably should swap to a pooled checker/emitresolver model and remove all those locks, just like we do for LS requests. Any questions an emit resolver answers really do just have to be lazy-calculation-safe under a concurrent model.
> Enable the noCheck emit consistency test

- internal/transformers/declarations/transform.go
If the length of the array is 1, the first item is at index 0, not index 1.
> Fix out of bounds error in `recreateBindingPattern`

- internal/checker/checker.go
This shaves off a few allocs in vscode.
> Don't allocate empty slice for named members

- cmd/tsgo/api.go
- cmd/tsgo/sys.go
- internal/api/api.go
- internal/api/host.go
- internal/api/server.go
- internal/checker/checker_test.go
- internal/compiler/host.go
- internal/compiler/program_test.go
- internal/execute/outputs.go
- internal/execute/system.go
- internal/execute/testsys_test.go
- internal/execute/tsc.go
- internal/execute/watch.go
- internal/execute/watcher.go
- internal/fourslash/fourslash.go
- internal/lsp/server.go
- internal/project/host.go
- internal/project/project.go
- internal/project/service.go
- internal/testutil/harnessutil/harnessutil.go
- internal/testutil/projecttestutil/projecttestutil.go
This removes the need to have options as part of the CompilerHost entirely, and is a cleanup we were thinking about ages ago.
The only notable change is that we now just use `\n` for the output newline on Windows, which I think is just fine.
Also clean up some other unused code in the host.
> Clean up host related code

- internal/compiler/fileloader.go
- internal/compiler/program.go
Noticed these while working on another issue; we should be skipping certain things when there are no root files (and no files in general).
> Fix no-file cases

- internal/ast/ast.go
- internal/parser/jsdoc.go
- internal/parser/parser.go
- internal/scanner/scanner.go
Grab bag of memory-allocation improvements:
```
goos: linux
goarch: amd64
pkg: github.com/microsoft/typescript-go/internal/parser
cpu: Intel(R) Core(TM) i9-10900K CPU @ 3.70GHz
│   old.txt   │              new.txt               │
│   sec/op    │   sec/op     vs base               │
Parse/empty.ts/tsc-20                                          507.2n ± 1%   515.4n ± 1%  +1.63% (p=0.000 n=10)
Parse/empty.ts/server-20                                       506.9n ± 2%   518.9n ± 1%  +2.38% (p=0.000 n=10)
Parse/checker.ts/tsc-20                                        46.67m ± 1%   46.68m ± 2%       ~ (p=0.971 n=10)
Parse/checker.ts/server-20                                     47.39m ± 2%   47.23m ± 1%       ~ (p=0.481 n=10)
Parse/dom.generated.d.ts/tsc-20 …
```
> Various memory allocation improvements

- .github/codeql/codeql-configuration.yml
This rule is now timing out in our repo. Not sure what changed.
> Ignore go/allocation-size-overflow in codeql

- internal/lsp/server.go
> lsp: Check diagnostic refresh capabilities against nil values & support more clients

- internal/lsp/lsproto/_generate/generate.mjs
- internal/lsp/lsproto/lsp.go
- internal/lsp/lsproto/lsp_generated.go
- internal/lsp/lsproto/lsp_test.go
Fixes #1425
Our union type decoding is broken because Go's JSON parsing has no mechanism to verify required properties. This meant that decoding into a union of structs is almost always guaranteed to succeed at choosing the first choice, except in the case where the types are incompatible.
This PR adds an unmarshal function to each structure that verifies that all required properties have been provided. This is not particularly efficient, but it does get the job done.
> Verify required properties in generated LSP code

- internal/ast/ast.go
- internal/ls/definition.go
- internal/ls/findallreferences.go
- internal/lsp/server.go
This PR implements the LSP `textDocument/implementation` request which enables the Go To Implementations command in VS Code.
> Implement Go To Implementations command

- internal/checker/checker.go
- internal/core/core.go
- testdata/baselines/reference/submodule/compiler/commonMissingSemicolons.errors.txt
- testdata/baselines/reference/submodule/compiler/commonMissingSemicolons.errors.txt.diff
- testdata/baselines/reference/submodule/compiler/constructorWithIncompleteTypeAnnotation.errors.txt
- testdata/baselines/reference/submodule/compiler/constructorWithIncompleteTypeAnnotation.errors.txt.diff
- testdata/baselines/reference/submodule/compiler/maximum10SpellingSuggestions.errors.txt
- testdata/baselines/reference/submodule/compiler/maximum10SpellingSuggestions.errors.txt.diff
- testdata/baselines/reference/submodule/conformance/parserRealSource11.errors.txt
- testdata/baselines/reference/submodule/conformance/parserRealSource11.errors.txt.diff
- testdata/baselines/reference/submodule/conformance/parserRealSource12.errors.txt
- testdata/baselines/reference/submodule/conformance/parserRealSource12.errors.txt.diff
- testdata/baselines/reference/submodule/conformance/parserRealSource13.errors.txt
- testdata/baselines/reference/submodule/conformance/parserRealSource13.errors.txt.diff
- testdata/baselines/reference/submodule/conformance/parserRealSource6.errors.txt
- testdata/baselines/reference/submodule/conformance/parserRealSource6.errors.txt.diff
- testdata/baselines/reference/submodule/conformance/parserRealSource7.errors.txt
- testdata/baselines/reference/submodule/conformance/parserRealSource7.errors.txt.diff
- testdata/baselines/reference/submodule/conformance/parserRealSource8.errors.txt
- testdata/baselines/reference/submodule/conformance/parserRealSource8.errors.txt.diff
- testdata/baselines/reference/submodule/conformance/parserRealSource9.errors.txt
- testdata/baselines/reference/submodule/conformance/parserRealSource9.errors.txt.diff
- testdata/baselines/reference/submodule/conformance/parserS7.6_A4.2_T1.errors.txt
- testdata/baselines/reference/submodule/conformance/parserS7.6_A4.2_T1.errors.txt.diff
- testdata/baselines/reference/submodule/conformance/parserharness.errors.txt
- testdata/baselines/reference/submodule/conformance/parserharness.errors.txt.diff
- testdata/baselines/reference/submodule/conformance/parserindenter.errors.txt
- testdata/baselines/reference/submodule/conformance/parserindenter.errors.txt.diff
- testdata/baselines/reference/submodule/conformance/scannerS7.6_A4.2_T1.errors.txt
- testdata/baselines/reference/submodule/conformance/scannerS7.6_A4.2_T1.errors.txt.diff
> Always include spelling suggestions in name errors

- internal/checker/checker.go
- internal/checker/flow.go
- internal/checker/nodebuilderimpl.go
- internal/checker/relater.go
- testdata/baselines/reference/submodule/compiler/abstractClassUnionInstantiation.types
- testdata/baselines/reference/submodule/compiler/abstractClassUnionInstantiation.types.diff
- testdata/baselines/reference/submodule/compiler/jsxComponentTypeErrors.errors.txt
- testdata/baselines/reference/submodule/compiler/jsxComponentTypeErrors.errors.txt.diff
> Consistently use len(x) != 0 checks for Signature.typeParameters

- internal/execute/tscwatch_test.go
- internal/execute/watcher.go
- testdata/baselines/reference/tscWatch/commandLineWatch/watch-with-tsconfig-and-incremental.js
> Fix nil host with watch and incremental

- internal/lsp/server.go
Fixes #1458.
Problem is twofold:
- When the param is truly empty, it will be `any(nil)`. But, you can't do `any(nil).(any)` without crashing (I still get things wrong as a 10 year Go veteran). If the params are `nil`, just ignore it. All params are either pointers or `any` anyway and types are checked before the handlers even run.
- I added code to make sure we returned an error for context cancellation. Except, I forgot to actually add in the code that actually sends the right LSP error back. So, they were getting sent as regular errors. Bad.
> Ignore empty params, fix cancellation errors

- internal/fourslash/fourslash.go
- internal/ls/completions.go
- internal/ls/completions_test.go
- internal/ls/definition.go
- internal/ls/findallreferences.go
- internal/ls/findallreferences_test.go
- internal/ls/findallreferencesexport_test.go
- internal/ls/format.go
- internal/ls/hover.go
- internal/ls/hover_test.go
- internal/ls/signaturehelp.go
- internal/ls/signaturehelp_test.go
- internal/ls/symbols.go
- internal/ls/untitled_test.go
- internal/lsp/lsproto/_generate/generate.mts
- internal/lsp/lsproto/lsp_generated.go
- internal/lsp/server.go
The result of my refactor is even more bugs.
This PR:
- Verifies that the LSP messages serialize in fourslash, which would have caught the problem.
- Undoes the `OrNull` -> pointer trick, which broke cases where we return a nil response.
- Pushes the response types further down, which finds places we are mishandling things.
I'd like to undo the undo of `OrNull` at some point, but right now I just want to stop the crashing.
> Fix more LSP related issues

- internal/ls/signaturehelp.go
- internal/ls/signaturehelp_test.go
This was crashing every time that the `context` was `nil`. 
Fixes #1435
Fixes #1467
> Fix for Signature help crash

- internal/api/proto.go
- internal/incremental/buildInfo.go
- internal/json/json.go
- internal/lsp/lsproto/_generate/generate.mts
- internal/lsp/lsproto/jsonrpc.go
- internal/lsp/lsproto/lsp_generated.go
- Replace `RawMessage` with `Value` (cleanup)
- Prevent double decode when checking required fields by using new `UnmarshalJSONFrom` and generated checks.
- Eliminate redundant unmarshal methods for enums; the defaults are fine as they are just values.
- Use `MarshalJSONTo` and `UnmarshalJSONFrom` in union/literal marshalling to avoid extra `[]byte` encoding; the former never produces an intermediary `[]byte`, and the latter slices out of the input buffer (zero copy).
- Use pointers for union type marshalling, now that it behaves consistently in v2.
> Optimize LSP marshalling via jsonv2 methods

- .github/workflows/create-cache.yml
> Enable long paths for windows in new create-cache workflow

- internal/tspath/path.go
When using project services, `ToFileNameLowerCase` is called 10, 312, 056 times on various paths, this means that it's incredibly hot path.
Since most projects won't hav e non-ascii filenames, we can optimize for this case. This yields up to a 5x perf improvement in some scenarios.
Please feel free to close, if the perf degregation againt non-ascii file paths outweighs the perf gains for the common case
| Test Case                     | Likelihood Category | Old (ns) | New (ns) |
| ----------------------------- | ------------------- | -------- | -------- |
| All lowercase ASCII short     | High                | 45.1     | 8.5      |
| All uppercase ASCII short     | Medium              | 71.8     | 37.9     |
| Mixed case ASCII short        | High                | 62.2     | 41.9     |
| …
> perf(tspath): optimize the fast path case for `ToFileNameLowerCase`

- internal/tspath/path.go
This pull request optimises `hasRelativePathSegment`, delivering a ~56% perf improvement.
This function is Called `27_628_418` times via tsgolint when linting vscode repo.
```
│   old.txt   │               new.txt               │
│   sec/op    │   sec/op     vs base                │
HasRelativePathSegment/foo/bar/baz-12                  29.10n ± 2%   14.79n ± 1%  -49.16% (p=0.000 n=10)
HasRelativePathSegment/./some/path-12                  2.065n ± 0%   2.039n ± 2%   -1.26% (p=0.022 n=10)
HasRelativePathSegment//foo/./bar/../../.-12           7.030n ± 0%   2.025n ± 0%  -71.20% (p=0.000 n=10)
HasRelativePathSegment/foo/foo/foo/foo/foo/...etc-12   9.076n ± 1%   2.308n ± 1%  -74.56% (p=0.000 n=10)
geomean                                                7.869n        3.446n       -56.21%
``` …
> perf(tspath): optimize `hasRelativePathSegment`

- .github/actions/setup-go/action.yml
See https://github.com/microsoft/typescript-go/issues/1571#issuecomment-3180604449
> Print out test diff on failure in create-cache

- .dprint.jsonc
- .github/actions/setup-go/action.yml
- .github/workflows/copilot-setup-steps.yml
- .github/workflows/create-cache.yml
- README.md
- _tools/customlint/testdata/go.mod
- _tools/go.mod
- go.mod
- internal/api/server.go
- internal/ast/kind.go
- internal/checker/types.go
- internal/core/compileroptions.go
- internal/core/languagevariant.go
- internal/core/scriptkind.go
- internal/core/tristate.go
- internal/diagnostics/diagnostics.go
- internal/fourslash/_scripts/convertFourslash.mts
- internal/lsp/lsproto/_generate/generate.mts
- internal/project/project.go
- internal/testutil/projecttestutil/projecttestutil.go
- internal/vfs/vfs.go
Goodbye, slow compile times
There is no need to update the release pipelines (not in this repo), since I configured them to extract the Go version from `go.mod`. Phew.
`golangci-lint` technically does not support this yet ([golangci/golangci-lint#5873](https://redirect.github.com/golangci/golangci-lint/issues/5873)), but since we custom build the binaries, it works fine.
> Update to Go 1.25

- .custom-gcl.yml
This one officially supports Go 1.25 now. I guess I could have waited a couple hours more on #1577. Oops.
> Update to golangci-lint v2.4.0

- internal/tspath/path.go
Replace `for _, c := range []byte(fileName)` with direct byte indexing to iterate over the string without allocating a new []byte slice. This removes an unnecessary allocation in both the ASCII fast path check and the lowercasing loop, improving performance and reducing GC pressure.
```
│ bench-to-file-name-lower-case-main.txt │ bench-to-file-name-lower-case-cbdcb60a5.txt │
│                 sec/op                 │        sec/op          vs base              │
ToFileNameLowerCase//path/to/file.ext-12                                         8.422n ± ∞ ¹            8.508n ± ∞ ¹       ~ (p=0.151 n=5)
ToFileNameLowerCase//PATH/TO/FILE.EXT-12                                         38.27n ± ∞ ¹            38.27n ± ∞ ¹       ~ (p=0.730 n=5)
ToFileNameLowerCase//path/to/FILE.EXT-12 …
```
> perf(tspath): void []byte allocation in ToFileNameLowerCase

- Herebyfile.mjs
- go.mod
- package.json
Before 1.25, we needed a postinstall to force Go to ignore `node_modules`. Now, we can just stick it in `go.mod`.
This also means we can now drop the `_` prefix on the dirs, but it's probably too late to change that.
> Use go.mod ignore directive instead of postinstall

- internal/debug/shared.go
I guess this is _not_ similar enough to `debugger;`, doing it without a debugger attach just does SIGTRAP. ☹️
> Remove runtime.Breakpoint call

- internal/checker/checker.go
- testdata/baselines/reference/compiler/implicitEmptyObjectType.errors.txt
- testdata/baselines/reference/compiler/implicitEmptyObjectType.symbols
- testdata/baselines/reference/compiler/implicitEmptyObjectType.types
- testdata/tests/cases/compiler/implicitEmptyObjectType.ts
> Prefer implicit `{}` over explicitly declared `{}` in subtype reduction

- internal/checker/nodebuilderimpl.go
- testdata/baselines/reference/submodule/compiler/defaultParameterAddsUndefinedWithStrictNullChecks.types
- testdata/baselines/reference/submodule/compiler/defaultParameterAddsUndefinedWithStrictNullChecks.types.diff
- testdata/baselines/reference/submodule/compiler/isolatedDeclarationsAddUndefined.js
- testdata/baselines/reference/submodule/compiler/isolatedDeclarationsAddUndefined.js.diff
- testdata/baselines/reference/submodule/compiler/isolatedDeclarationsAddUndefined.types
- testdata/baselines/reference/submodule/compiler/isolatedDeclarationsAddUndefined.types.diff
- testdata/baselines/reference/submodule/compiler/verbatim-declarations-parameters.types
- testdata/baselines/reference/submodule/compiler/verbatim-declarations-parameters.types.diff
Noticed this when looking at #1600. In Strada, this is unconditional if the type node isn't being reused.
> Fix addUndefinedForParameter check location

- internal/execute/build/buildtask.go
- internal/execute/build/host.go
- internal/execute/incremental/affectedfileshandler.go
- internal/execute/incremental/emitfileshandler.go
- internal/execute/incremental/program.go
- internal/execute/tsc.go
- internal/execute/tsc/compile.go
- internal/execute/tsctests/runner.go
- internal/execute/tsctests/sys.go
- internal/execute/watcher.go
Parity with Strada:
Release program after emit - (this releases program all together and snapshot for now but it will be retained for --w like in strada)
Cache only source files for d.ts and json files as those are the ones that are exepected to be reused
Fixes #1622
> Release program after finishing program emit, Only cache dts and json source files

- .github/copilot-instructions.md
- Herebyfile.mjs
The instructions for Copilot were wrong/suboptimal.
- `hereby --list` doesn't exist. It's `hereby --tasks`. Fix that.
- Once this works, we need good descriptions on the tasks. Add those, and hide tasks that nobody should be running at this point (and definitely not Copilot).
- `hereby build` doesn't build the project, it's just another way to build the `tsgo` binary, which is not needed for tests. Fix the description.
- Clarify the kinds of tests we use, to hopefully promote running `Local` for new tests.
> Fix copilot instructions using the wrong commands

- internal/compiler/program.go
- internal/execute/tsctests/tscbuild_test.go
- testdata/baselines/reference/compiler/processingDiagnosticSkipLibCheck.js
- testdata/baselines/reference/compiler/processingDiagnosticSkipLibCheck.symbols
- testdata/baselines/reference/compiler/processingDiagnosticSkipLibCheck.types
- testdata/baselines/reference/tsbuild/demo/in-bad-ref-branch-reports-the-error-about-files-not-in-rootDir-at-the-import-location.js
- testdata/baselines/reference/tsbuild/resolveJsonModule/include-only.js
- testdata/baselines/reference/tsc/libraryResolution/unknown-lib.js
- testdata/baselines/reference/tsc/projectReferences/errors-when-a-file-is-outside-the-rootdir.js
- testdata/baselines/reference/tsc/projectReferences/errors-when-the-file-list-is-not-exhaustive.js
- testdata/tests/cases/compiler/processingDiagnosticSkipLibCheck.ts
In Corsa, `GetProgramDiagnostics` was including all diagnostics of the `includeProcessor`, which includes `/// <reference ...>` diagnostics and resolution diagnostics. Because we did that, an error e.g. in a bad `/// <reference type="non-existent"/>` in a lib file would be included in the output of a command line execution even if the project had `skipLibCheck: true`.
This PR changes this so that `GetProgramDiagnostics` now only includes *global* `includeProcessor` diagnostics.
This is basically what Strada did (see `program.getCombinedDiagnostics` there).
The file-specific `includeProcessor` diagnostics are now obtained via `getSemanticDiagnosticsForFile`. This is also what Strada did.
The result is that in `getSemanticDiagnosticsForFile`, we have a chance to check if that file should be …
> Handle processing diagnostics similar to Strada

- internal/project/configfilechanges_test.go
- internal/project/extendedconfigcache.go
- internal/project/project_test.go
- internal/project/projectcollectionbuilder.go
- internal/project/projectcollectionbuilder_test.go
- internal/tsoptions/tsconfigparsing.go
- Fixes an issue with ATA caching that could cause a "No project found for file" error message when opening JS files in inferred projects
- Fixes a crash when a tsconfig.json `"extends"` target doesn't exist
- Fixes #1630 (pretty sure)
> Fix three snapshots bugs

- internal/compiler/program.go
- internal/execute/incremental/program.go
- testdata/baselines/reference/tsbuild/demo/in-bad-ref-branch-reports-the-error-about-files-not-in-rootDir-at-the-import-location.js
- testdata/baselines/reference/tsbuild/resolveJsonModule/include-only.js
- testdata/baselines/reference/tsc/libraryResolution/unknown-lib.js
- testdata/baselines/reference/tsc/projectReferences/errors-when-a-file-is-outside-the-rootdir.js
- testdata/baselines/reference/tsc/projectReferences/errors-when-the-file-list-is-not-exhaustive.js
#1628 started adding program diagnostics to semantic diagnostic reporting like Strada
This handles incremental scenarios like Strada where we don't store program diagnostics to file because we don't know if they change or not if program structure changes and semantic diagnostics from cache are used
> Do not store include processing diagnsotics in buildInfo

- internal/core/bfs.go
- internal/core/bfs_test.go
- internal/project/project.go
- internal/project/projectcollection.go
- internal/project/projectcollectionbuilder.go
- internal/project/projectcollectionbuilder_test.go
We were doing an infinite BFS in the project collection builder while looking for a tsconfig for a given file. The loop happened because the BFS node type included a pointer to a `logger`, which changed every time we computed the neighbors of a node, and so no node was ever considered as already visited, even if we had already visited its corresponding tsconfig.
> Fix BFS loop during config lookup

- internal/fourslash/tests/util/util.go
- internal/ls/completions.go
- internal/stringutil/compare.go
Haven't removed the collator package because presumably we'll need it for organize imports.
[Collator sorting is slow](#1582), and using non-locale aware sorting doesn't seem like it would noticeably impact the user experience. For instance, vscode sorts its completion items by using regular string comparison on labels: https://github.com/microsoft/vscode/blob/8ee3a001179ba5153d152a3256c10158e18e42f9/src/vs/editor/contrib/suggest/browser/suggest.ts#L338
> Don't use locale-aware sorting in completions

- internal/tsoptions/parsedcommandline.go
- internal/tsoptions/parsedcommandline_test.go
- internal/tsoptions/tsconfigparsing.go
Discovered this while investigating something else
> Fix out of bounds panic when tsconfig "files" contains duplicates

- internal/diagnostics/diagnostics_generated.go
- internal/diagnostics/extraDiagnosticMessages.json
- internal/execute/build/buildtask.go
- internal/execute/tsctests/tscbuild_test.go
- testdata/baselines/reference/tsbuild/programUpdates/when-root-is-source-from-project-reference-with-composite.js
- testdata/baselines/reference/tsbuild/programUpdates/when-root-is-source-from-project-reference.js
- testdata/baselines/reference/tsbuild/resolveJsonModule/include-only-with-json-without-rootDir-but-outside-configDirectory-non-composite.js
> Ignore timestamp update errors like in strada

- internal/jsnum/pseudobigint_test.go
Adds unit tests for ParsePseudoBigInt across non-decimal bases, responding to the
inline TODO ("tests for other bases") in internal/jsnum/pseudobigint_test.go.
- Binary (0b/0B), Octal (0o/0O), Hex (0x/0X)
- With/without underscore separators
- Small-number cases (0, 1, 10, 255)
No behavior changes; tests pass with the current implementation.
> test(jsnum): add binary/oct/hex BigInt cases including underscores and uppercase prefixes

- internal/checker/emitresolver.go
- internal/printer/emitresolver.go
- internal/transformers/declarations/transform.go
- testdata/baselines/reference/compiler/enumMemberInterfacePropertyDeclarationEmit.js
- testdata/baselines/reference/submodule/compiler/isolatedDeclarationErrorsClasses.js
- testdata/baselines/reference/submodule/compiler/isolatedDeclarationErrorsClasses.js.diff
- testdata/tests/cases/compiler/enumMemberInterfacePropertyDeclarationEmit.ts
This was uncovered while trying to migrate an internal team onto `tsgo --build`.
> Fix isolatedDeclarations emit of computed property names in interfaces

- internal/parser/parser.go
- testdata/baselines/reference/compiler/jsSpeculativeParsingError.symbols
- testdata/baselines/reference/compiler/jsSpeculativeParsingError.types
- testdata/tests/cases/compiler/jsSpeculativeParsingError.ts
> Include jsDiagnostics in parser state mark/rewind

- internal/checker/relater.go
- testdata/baselines/reference/compiler/freshObjectLiteralSubtype.symbols
- testdata/baselines/reference/compiler/freshObjectLiteralSubtype.types
- testdata/tests/cases/compiler/freshObjectLiteralSubtype.ts
This PR modifies type relationship checking such that types with extra properties are never subtypes of fresh object literals. This in turn ensures that fresh object literal types are subtypes of regular object types with optional properties that aren't specified in the fresh object literal types. For example, with this PR the fresh object literal type `{ valid: boolean }` is a subtype of the regular type `{ valid: boolean; msg?: undefined; }`, but not vice-versa, where previously both were subtypes of each other.
Fixes #1742.
> Types with extra properties are never subtypes of fresh object literals

- internal/checker/relater.go
- testdata/baselines/reference/compiler/freshObjectLiteralSubtype.symbols
- testdata/baselines/reference/compiler/freshObjectLiteralSubtype.types
- testdata/tests/cases/compiler/freshObjectLiteralSubtype.ts
> Revert back to isObjectLiteralType check

- internal/checker/checker.go
- internal/checker/relater.go
- testdata/baselines/reference/compiler/missingDiscriminants2.errors.txt
- testdata/baselines/reference/compiler/missingDiscriminants2.symbols
- testdata/baselines/reference/compiler/missingDiscriminants2.types
- testdata/tests/cases/compiler/missingDiscriminants2.ts
Implements what I describe [here](https://github.com/microsoft/typescript-go/issues/1727#issuecomment-3341831052).
Fixes #1727.
> Fix translation error that disabled union discrimination optimization

- internal/checker/checker.go
- internal/checker/flow.go
- testdata/baselines/reference/compiler/expandoFunctionAsAssertion.symbols
- testdata/baselines/reference/compiler/expandoFunctionAsAssertion.types
- testdata/tests/cases/compiler/expandoFunctionAsAssertion.ts
> Permit expando property function with return type annotation as assertion

- internal/checker/flow.go
- testdata/baselines/reference/submodule/conformance/dependentDestructuredVariablesWithExport.types
- testdata/baselines/reference/submodule/conformance/dependentDestructuredVariablesWithExport.types.diff
ports https://github.com/microsoft/TypeScript/pull/59673
> Port "make exported destructured discriminated union narrowing work"

- internal/ls/string_completions.go
ports https://github.com/microsoft/TypeScript/pull/60272
I still can't enable the related tests because in Corsa there is a pre-existing issue causing a label mismatch on the expected completion entry
> Port "Provide string completions for `in` keyword checks"

- internal/tsoptions/declscompiler.go
I forgot to change this when I ported in the flag and defaulted it to `false`.
> Mark libReplacement default as false

- internal/parser/parser.go
- testdata/baselines/reference/submodule/conformance/importAttributes10.errors.txt
- testdata/baselines/reference/submodule/conformance/importAttributes10.errors.txt.diff
- testdata/baselines/reference/submodule/conformance/importAttributes10.js
- testdata/baselines/reference/submodule/conformance/importAttributes10.js.diff
ports https://github.com/microsoft/TypeScript/pull/61920
> Port "Allow trailing commas after import attributes in `ImportType`"

- internal/checker/checker.go
ports https://github.com/microsoft/TypeScript/pull/60857
It seems this isn't strictly needed right now. Likely, reparsing fixed the original issue already but I think it might still be a good idea to pick up this change for the sake of code parity between Strada and Corsa
> Port "Stop reassigning `.valueDeclaration` to avoid replacing earlier declarations with late ones"

- internal/checker/emitresolver.go
ports https://github.com/microsoft/TypeScript/pull/61352
It seems this isn't strictly needed right now. Likely, reparsing fixed the original issue already but I think it might still be a good idea to pick up this change for the sake of code parity between Strada and Corsa
> Port "Fixed crash in `hasVisibleDeclarations` related to binding elements"

- internal/ls/completions.go
There is no change in tests (yet) because all related tests fail at the first `assertDeepEqual` call in `verifyCompletionItem` for other reasons. So the code never reaches `assertDeepEqual` targeting `.SortText`
ports https://github.com/microsoft/TypeScript/pull/61945
> Port "Fix Symbol completion priority and cursor positioning"

- internal/ast/utilities.go
- internal/checker/checker.go
- internal/checker/grammarchecks.go
- internal/checker/utilities.go
- internal/ls/documenthighlights.go
Fixes #1836
This is just a pure port. Seemingly no tests hit this.
> Fix getAsyncAndAwaitOccurrences function handling
